carts:
    container:
        name: carts
    image:
        pullPolicy: IfNotPresent
        repository: docker.io/keptnexamples/carts
        tag: 0.8.1
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 80
        internalPort: 8080
        name: carts
        type: LoadBalancer
cartsDb:
    container:
        name: carts-db
    image:
        pullPolicy: IfNotPresent
        repository: mongo
    replicaCount: 1
    service:
        externalPort: 27017
        internalPort: 27017
        name: carts-db
